{% set name = "n50" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quadram-institute-bioscience/n50/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

build:
  number: 0
  run_exports:
    - {{ name }} ={{ version }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - n50 --version | grep {{ version }}
    - n50_simseqs --version | grep  {{ version }}

about:
  home: https://github.com/quadram-institute-bioscience/n50
  license: MIT
  license_file: LICENSE
  summary: "A command-line tool to calculate the N50 value of a set of sequences and other utilities."
  description: |
    This repository provides tools for N50 calculation and dataset simulation.
  doc_url: https://github.com/quadram-institute-bioscience/n50/blob/main/README.md
  dev_url: https://github.com/quadram-institute-bioscience/n50

extra:
  recipe-maintainers:
    - telatin
